### ISSUE TITLE
Security Policy and other out-of date files

### ISSUE THREAD

**Issue by Okmeque1** [GamerSoft24/Software#17]
Some files do NOT live to their standards as files get added but do not get added to PROGRAMS.MD or have spelling mistakes(which isn't important, just first point) 

I expect this to be resolved by the 23/10/2023 as stated by your security policy. If you fail to do so, I will change them myself.

:) Okmeque1

*Not a big issue, just be more attentive please*

**Comment by GamerSoft24** [comment]
Hello Okmeque1,
Please could you create a pull request of it? I will be working on it but it would be really nice!
GamerSoft24.

**Comment by Okmeque1** [comment]
Alright then. Thank you for responding.

-Okmeque1
