### ISSUE TITLE
SMS - Security Management System WAY too long!

### ISSUE THREAD

**Issue by GamerAlt24** [GamerSoft24/Software#24]
SMS - Security Management System **WAY** _too long!_ You should use functions [def ...()] e.g. def sms_main().
Hope you can understand,
GamerAlt24 - The famous ALT of GamerSoft24.

**Comment by SutoEXEC** [comment]
Hello GamerAlt24,
We will be editing SMS and it will be updated in the past 4 days.
Thank you for reporting!
SutoEXEC from AUTOEXEC.BAT--MS-DOS.

**Comment by Okmeque1** [comment]
Hello @GamerAlt24,
Your request is valid and the program will be updated. Please note that it may take a while for the program to update.
- The Okmeque1

**Comment by GamerSoft24** [comment]
@GamerAlt24 @Okmeque1 @SutoEXEC, Issue #24 can now be closed. "SMS Renewal on Issue by GamerAlt24 - Step 2 (Last)" was the last commit (2/2) with code [ac2255c](https://github.com/GamerSoft24/Software/commit/ac2255cf0b82b46e25942fe5a5503c9e9eae445b).
