### ISSUE TITLE
Error handling in PySoft?

### ISSUE THREAD

**Issue by GmaerSoft42** [GamerSoft24/Software#34]
**Is your feature request related to a problem? Please describe.**
I've already done a lot of the error handling work, but I don't see it in new programs.

**Describe the solution you'd like**
Simple. Add : 
``` try:
           {codehere}
    except BaseException:
           print("ERROR : 770A\nA random exception has occured.")
```
Don't even have to put the full complement of error handling from the [error chart](https://github.com/GamerSoft24/Software/blob/Main/Errors%20chart.md)
**Describe alternatives you've considered**
None, apart when the program terminates because I put a typo in my filename

**Additional context**
See your SMS in PySoft/Utilities

**Comment by GmaerSoft42** [comment]
oh yes gmaersoft42 exists now

**Comment by GamerSoft24** [comment]
UARTE

**Comment by GmaerSoft42** [comment]
uarte

**Comment by SutoEXEC** [comment]
@GmaerSoft42 @Okmeque1 can u please sort it off for me? I will edit directly from there and it would be very nice of you. call it `pysoft-error-handling-upd` or something and you can include your:
``` 
      {codehere}
      except BaseException:
            print("ERROR: 770A\nA random exception has occured.")
```
with Error without capital and without a space after error please (e.g Error: 770A\n A random blablabla...)
Thank you,
SutoEXEC (AUTOEXEC.BAT)

**Comment by GamerSoft24** [comment]
we are currenlty sorting this out @Okmeque1

**Comment by GamerSoft24** [comment]
@Okmeque1 @SutoEXEC where more should i add error handling? (sms and ipcmd now have error handling)

**Comment by Okmeque1** [comment]
> @Okmeque1 @SutoEXEC where more should i add error handling? (sms and ipcmd now have error handling)

do it in every python prog

**Comment by GamerSoft24** [comment]
Bunch of updates on PySoft Error handling. Same with PR #36

**Comment by GamerSoft24** [comment]
> > [@Okmeque1](https://github.com/Okmeque1) [@SutoEXEC](https://github.com/SutoEXEC) where more should i add error handling? (sms and ipcmd now have error handling)
> 
> do it in every python prog

yep okay!

**Comment by GamerSoft24** [comment]
all good, issue can now be closed
