### ISSUE TITLE
[Bug]: GmaerSoft42?

### ISSUE THREAD

**Issue by GS-ST** [GamerSoft24/Software#56]
### Contact Details

gsst2401@gmail.com

### What happened?

Why does it lead to GmaerSoft42 github? I thought this was GamerSoft github.
![image](https://github.com/GamerSoft24/Software/assets/147323945/2d626941-ced2-4722-8286-82ad92dba89f)

### What browser(s) are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GS-ST** [comment]
maybe an april fool joke that ain't been removed

**Comment by GmaerSoft42** [comment]
_**You have been haunted by GmaerSoft42. Be gone GS-ST!**_

**Comment by Okmeque1** [comment]
Now Fixed!

**Comment by GamerSoft24** [comment]
erm
